version: "2"
services:

  adguardhome:
    image: adguard/adguardhome
    container_name: Adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped

volumes:
  adguard_conf:
  adguard_work: